In [1]:
# import libraries
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
# Add the parent directory to the system path 
import os
import sys
sys.path.append(os.path.abspath(os.path.join('..')))

In [3]:
# importing modules from scripts 
from scripts.database_connection import *
from scripts.data_processing import *

In [4]:
# Load the data from the database
df = load_data()

Successfully connected to the database.
Successfully loaded 150001 records.

In [5]:
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [6]:
# tellco data field descriptions
df_field_desc = pd.read_excel("../data/data/Field Descriptions.xlsx")

df_field_desc

,Fields,Description
0,bearer id,xDr session identifier
1,Dur. (ms),Total Duration of the xDR (in ms)
2,Start,Start time of the xDR (first frame timestamp)
3,Start ms,Milliseconds offset of start time for the xDR ...
4,End,End time of the xDR (last frame timestamp)
5,End ms,Milliseconds offset of end time of the xDR (la...
6,Dur. (s),Total Duration of the xDR (in s)
7,IMSI,International Mobile Subscriber Identity
8,MSISDN/Number,MS International PSTN/ISDN Number of mobile - ...
9,IMEI,International Mobile Equipment Identity
10,Last Location Name,User location call name (2G/3G/4G) at the end ...
11,Avg RTT DL (ms),Average Round Trip Time measurement Downlink d...
12,Avg RTT UL (ms),Average Round Trip Time measurement Uplink dir...
13,Avg Bearer TP DL (kbps),Average Bearer Throughput for Downlink (kbps) ...
14,Avg Bearer TP UL (kbps),Average Bearer Throughput for uplink (kbps) - ...
15,TCP DL Retrans. Vol (Bytes),TCP volume of Downlink packets detected as ret...
16,TCP UL Retrans. Vol (Bytes),TCP volume of Uplink packets detected as retra...
17,DL TP < 50 Kbps (%),Duration ratio when Bearer Downlink Throughput...
18,50 Kbps < DL TP < 250 Kbps (%),Duration ratio when Bearer Downlink Throughput...
19,250 Kbps < DL TP < 1 Mbps (%),Duration ratio when Bearer Downlink Throughput...
20,DL TP > 1 Mbps (%),Duration ratio when Bearer Downlink Throughput...
21,UL TP < 10 Kbps (%),Duration ratio when Bearer Uplink Throughput < â€¦.
22,10 Kbps < UL TP < 50 Kbps (%),Duration ratio when Bearer Uplink Throughput r...
23,50 Kbps < UL TP < 300 Kbps (%),Duration ratio when Bearer Uplink Throughput r...
24,UL TP > 300 Kbps (%),Duration ratio when Bearer Uplink Throughput > â€¦.
25,HTTP DL (Bytes),HTTP data volume (in Bytes) received by the MS...
26,HTTP UL (Bytes),HTTP data volume (in Bytes) sent by the MS dur...
27,Activity Duration DL (ms),Activity Duration for downlink (ms) - excludin...
28,Activity Duration UL (ms),Activity Duration for uplink (ms) - excluding ...
29,Dur. (ms).1,Total Duration of the xDR (in ms)
30,Handset Manufacturer,Handset manufacturer
31,Handset Type,Handset type of the mobile device
32,Nb of sec with 125000B < Vol DL,Number of seconds with IP Volume DL >
33,Nb of sec with 1250B < Vol UL < 6250B,Number of seconds with IP Volume UL between â€¦
34,Nb of sec with 31250B < Vol DL < 125000B,Number of seconds with IP Volume DL between â€¦
35,Nb of sec with 37500B < Vol UL,Number of seconds with IP Volume UL >
36,Nb of sec with 6250B < Vol DL < 31250B,Number of seconds with IP Volume DL between â€¦
37,Nb of sec with 6250B < Vol UL < 37500B,Number of seconds with IP Volume UL between â€¦
38,Nb of sec with Vol DL < 6250B,Number of seconds with IP Volume DL <
39,Nb of sec with Vol UL < 1250B,Number of seconds with IP Volume UL <
40,Social Media DL (Bytes),Social Media data volume (in Bytes) received b...
41,Social Media UL (Bytes),Social Media data volume (in Bytes) sent by th...
42,YouTube DL (Bytes),YouTube data volume (in Bytes) received by the...
43,YouTube UL (Bytes),YouTube data volume (in Bytes) sent by the MS ...
44,Netflix DL (Bytes),Netflix data volume (in Bytes) received by the...
45,Netflix UL (Bytes),Netflix data volume (in Bytes) sent by the MS ...
46,Google DL (Bytes),Google data volume (in Bytes) Received by the ...
47,Google UL (Bytes),Google data volume (in Bytes) sent by the MS d...
48,Email DL (Bytes),Email data volume (in Bytes) Received by the M...
49,Email UL (Bytes),Email data volume (in Bytes) sent by the MS du...
50,Gaming DL (Bytes),Gaming data volume (in Bytes) Received by the ...
51,Gaming UL (Bytes),Gaming data volume (in Bytes) sent by the MS d...
52,Other DL,Other data volume (in Bytes) received by the M...
53,Other UL,Other data volume (in Bytes) sent by the MS du...
54,Total DL (Bytes),Data volume (in Bytes) received by the MS duri...
55,Total UL (Bytes),Data volume (in Bytes) sent by the MS during t...

In [7]:
#  size of the data
df.shape

(150001, 55)

### Basic Statistical Analysis

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [9]:
# descriptive statistics
df.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,...,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,...,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,...,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,...,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,...,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [10]:
# check for missing values 
df.isnull().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [11]:
# percentage of missing values 
calculate_missing_percentage(df)

The dataset has 12.5% missing values.

In [12]:
# Check for duplicate rows
duplicate_rows = df.duplicated()

# Print the number of duplicate rows
print(f"Number of duplicate rows: {duplicate_rows.sum()}")

Number of duplicate rows: 0

The below table presents a summary of missing data for various columns in a dataset.

In [13]:
# total missing values and it's percentage 
display_missing_values(df)

The dataframe contains 55 columns.
41 columns have missing values.

,Missing Values,% of Total Values,Data Type
Nb of sec with 37500B < Vol UL,130254,86.84,float64
Nb of sec with 6250B < Vol UL < 37500B,111843,74.56,float64
Nb of sec with 125000B < Vol DL,97538,65.02,float64
TCP UL Retrans. Vol (Bytes),96649,64.43,float64
Nb of sec with 31250B < Vol DL < 125000B,93586,62.39,float64
Nb of sec with 1250B < Vol UL < 6250B,92894,61.93,float64
Nb of sec with 6250B < Vol DL < 31250B,88317,58.88,float64
TCP DL Retrans. Vol (Bytes),88146,58.76,float64
HTTP UL (Bytes),81810,54.54,float64
HTTP DL (Bytes),81474,54.32,float64
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
Handset Manufacturer,572,0.38,object
Handset Type,572,0.38,object
IMEI,572,0.38,float64
IMSI,570,0.38,float64
Start,1,0.00,object
Start ms,1,0.00,float64
End,1,0.00,object
End ms,1,0.00,float64
Dur. (ms),1,0.00,float64
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Dur. (ms).1,1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

## Handling Missing Values

for Categorical columns ('Last Location Name', 'Handset Manufacturer', 'Handset Type') I used mode imputation (most frequent value) as these are likely to be categorical variables where mean or median imputation wouldn't make sense.

In [14]:
# Handle categorical columns
categorical_columns = ['Last Location Name', 'Handset Manufacturer', 'Handset Type']
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after handling categorical columns:")
print(df[categorical_columns].isnull().sum())

Missing values after handling categorical columns:
Last Location Name      0
Handset Manufacturer    0
Handset Type            0
dtype: int64

 For columns with very few missing values (<1%), I used mean imputation as it's computationally efficient and won't significantly affect the distribution for such a small percentage.

In [15]:
# Handle numeric columns with low missing values
numeric_columns = df.select_dtypes(include=['float64']).columns
for col in numeric_columns:
    if df[col].isnull().sum() / len(df) < 0.01:
        df[col] = df[col].fillna(df[col].mean())

print("\nMissing values in numeric columns after handling low-missing columns:")
print(df[numeric_columns].isnull().sum())

Missing values in numeric columns after handling low-missing columns:
Bearer Id                                        0
Start ms                                         0
End ms                                           0
Dur. (ms)                                        0
IMSI                                             0
MSISDN/Number                                    0
IMEI                                             0
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          0
Avg Bearer TP UL (kbps)                          0
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                              0
50 Kbps < DL TP < 250 Kbps (%)                   0
250 Kbps < DL TP < 1 Mbps (%)                    0
DL TP > 1 Mbps (%)                               0
UL TP < 10 Kbps (%)                              0
10 Kbps < UL TP < 50 Kbps (%)                    0
50 Kbps < UL TP < 300 Kbps (%)                   0
UL TP > 300 Kbps (%)                             0
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        0
Activity Duration UL (ms)                        0
Dur. (ms).1                                      0
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                    0
Nb of sec with Vol UL < 1250B                    0
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 0
Total DL (Bytes)                                 0
dtype: int64

#### Columns with high percentage of missing values (>50%): tcp and traffic variables 
 - We need TCP variables for User Experience Analytics. instead of dropping the columns for tcp and traffic variables we use MICE (Multivariate Imputation by Chained Equations). It is well-suited for handling missing values in multiple related variables. It works by modeling each feature with missing values as a function of other features in a round-robin fashion.

In [18]:
# Handle TCP and traffic columns using Iterative Imputer
tcp_traffic_columns = [
    'TCP UL Retrans. Vol (Bytes)', 'TCP DL Retrans. Vol (Bytes)',
    'Nb of sec with 37500B < Vol UL', 'Nb of sec with 6250B < Vol UL < 37500B',
    'Nb of sec with 125000B < Vol DL', 'Nb of sec with 31250B < Vol DL < 125000B',
    'Nb of sec with 1250B < Vol UL < 6250B', 'Nb of sec with 6250B < Vol DL < 31250B',
    'HTTP UL (Bytes)', 'HTTP DL (Bytes)'
]

imp = IterativeImputer(max_iter=10, random_state=0)
df[tcp_traffic_columns] = imp.fit_transform(df[tcp_traffic_columns])

print("\nMissing values in TCP and traffic columns after Iterative Imputation:")
print(df[tcp_traffic_columns].isnull().sum())

Missing values in TCP and traffic columns after Iterative Imputation:
TCP UL Retrans. Vol (Bytes)                 0
TCP DL Retrans. Vol (Bytes)                 0
Nb of sec with 37500B < Vol UL              0
Nb of sec with 6250B < Vol UL < 37500B      0
Nb of sec with 125000B < Vol DL             0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 6250B < Vol DL < 31250B      0
HTTP UL (Bytes)                             0
HTTP DL (Bytes)                             0
dtype: int64

 ID columns ('Bearer Id', MSISDN/Number', 'IMEI', 'IMSI')
 These are likely unique identifiers, and imputing with mean or mode wouldn't make sense.so we drop the rows for the indentifier columns.

In [21]:
#  Drop empty rows for the identifier columns
identifier_cols = ['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI']
df = df.dropna(subset=identifier_cols)

In [23]:
 #check for missing values
print("\n check for missing values:")
print(df.isnull().sum())

 check for missing values:
Bearer Id                                       0
Start                                           1
Start ms                                        0
End                                             1
End ms                                          0
Dur. (ms)                                       0
IMSI                                            0
MSISDN/Number                                   0
IMEI                                            0
Last Location Name                              0
Avg RTT DL (ms)                             27829
Avg RTT UL (ms)                             27812
Avg Bearer TP DL (kbps)                         0
Avg Bearer TP UL (kbps)                         0
TCP DL Retrans. Vol (Bytes)                     0
TCP UL Retrans. Vol (Bytes)                     0
DL TP < 50 Kbps (%)                             0
50 Kbps < DL TP < 250 Kbps (%)                  0
250 Kbps < DL TP < 1 Mbps (%)                   0
DL TP > 1 Mbps (%)                              0
UL TP < 10 Kbps (%)                             0
10 Kbps < UL TP < 50 Kbps (%)                   0
50 Kbps < UL TP < 300 Kbps (%)                  0
UL TP > 300 Kbps (%)                            0
HTTP DL (Bytes)                                 0
HTTP UL (Bytes)                                 0
Activity Duration DL (ms)                       0
Activity Duration UL (ms)                       0
Dur. (ms).1                                     0
Handset Manufacturer                            0
Handset Type                                    0
Nb of sec with 125000B < Vol DL                 0
Nb of sec with 1250B < Vol UL < 6250B           0
Nb of sec with 31250B < Vol DL < 125000B        0
Nb of sec with 37500B < Vol UL                  0
Nb of sec with 6250B < Vol DL < 31250B          0
Nb of sec with 6250B < Vol UL < 37500B          0
Nb of sec with Vol DL < 6250B                   0
Nb of sec with Vol UL < 1250B                   0
Social Media DL (Bytes)                         0
Social Media UL (Bytes)                         0
Google DL (Bytes)                               0
Google UL (Bytes)                               0
Email DL (Bytes)                                0
Email UL (Bytes)                                0
Youtube DL (Bytes)                              0
Youtube UL (Bytes)                              0
Netflix DL (Bytes)                              0
Netflix UL (Bytes)                              0
Gaming DL (Bytes)                               0
Gaming UL (Bytes)                               0
Other DL (Bytes)                                0
Other UL (Bytes)                                0
Total UL (Bytes)                                0
Total DL (Bytes)                                0
dtype: int64

 for the columns having about 18% missing values again i impute missing values in 'Avg RTT DL (ms)' and Avg RTT UL (ms) with the mean

In [24]:
# Impute missing values in 'Avg RTT DL (ms)' with the mean
df['Avg RTT DL (ms)']=df['Avg RTT DL (ms)'].fillna(df['Avg RTT DL (ms)'].mean())

# Impute missing values in 'Avg RTT UL (ms)' with the mean
df['Avg RTT UL (ms)']=df['Avg RTT UL (ms)'].fillna(df['Avg RTT UL (ms)'].mean())

In [31]:
# percentage of missing values 
calculate_missing_percentage(df)

The dataset has 0.0% missing values.

### Handling Outliers 

 I used Interquartile Range (IQR) method to detect and handle outliers, as it's robust and works well for various distributions.

In [32]:
# Handle outliers in specified  numeric columns of a DataFrame.
numeric_columns = df.select_dtypes(include=[np.number]).columns
df = handle_outliers(df, numeric_columns, method='iqr', threshold=1.5)

Convert categorical columns in the DataFrame df from object type to string data type

In [33]:
for col in categorical_columns:
    df[col] = (df[col].astype('string'))
    
print(df[categorical_columns].head())

      Last Location Name Handset Manufacturer                 Handset Type
0  9.16456699548519E+015              Samsung   Samsung Galaxy A5 Sm-A520F
1                L77566A              Samsung  Samsung Galaxy J5 (Sm-J530)
2                D42335A              Samsung     Samsung Galaxy A8 (2018)
3                T21824A            undefined                    undefined
4                D88865A              Samsung             Samsung Sm-G390F

convert date and time column to datetime format, which will handle any potential missing values by converting them to NaT (Not a Time).

In [34]:
 #Handle date and time columns
time_columns = ['Start', 'End']
for col in time_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 150001 non-null  float64
 1   Start                                     150000 non-null  datetime64[ns]
 2   Start ms                                  150001 non-null  float64
 3   End                                       150000 non-null  datetime64[ns]
 4   End ms                                    150001 non-null  float64
 5   Dur. (ms)                                 150001 non-null  float64
 6   IMSI                                      150001 non-null  float64
 7   MSISDN/Number                             150001 non-null  float64
 8   IMEI                                      150001 non-null  float64
 9   Last Location Name                        150001 non-null  string
 10  Avg RTT DL (ms)                           150001 non-null  float64
 11  Avg RTT UL (ms)                           150001 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150001 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150001 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               150001 non-null  float64
 15  TCP UL Retrans. Vol (Bytes)               150001 non-null  float64
 16  DL TP < 50 Kbps (%)                       150001 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            150001 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             150001 non-null  float64
 19  DL TP > 1 Mbps (%)                        150001 non-null  float64
 20  UL TP < 10 Kbps (%)                       150001 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             150001 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            150001 non-null  float64
 23  UL TP > 300 Kbps (%)                      150001 non-null  float64
 24  HTTP DL (Bytes)                           150001 non-null  float64
 25  HTTP UL (Bytes)                           150001 non-null  float64
 26  Activity Duration DL (ms)                 150001 non-null  float64
 27  Activity Duration UL (ms)                 150001 non-null  float64
 28  Dur. (ms).1                               150001 non-null  float64
 29  Handset Manufacturer                      150001 non-null  string
 30  Handset Type                              150001 non-null  string
 31  Nb of sec with 125000B < Vol DL           150001 non-null  float64
 32  Nb of sec with 1250B < Vol UL < 6250B     150001 non-null  float64
 33  Nb of sec with 31250B < Vol DL < 125000B  150001 non-null  float64
 34  Nb of sec with 37500B < Vol UL            150001 non-null  float64
 35  Nb of sec with 6250B < Vol DL < 31250B    150001 non-null  float64
 36  Nb of sec with 6250B < Vol UL < 37500B    150001 non-null  float64
 37  Nb of sec with Vol DL < 6250B             150001 non-null  float64
 38  Nb of sec with Vol UL < 1250B             150001 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150001 non-null  float64
 54  Total DL (Bytes)                          150001 non-null  float64
dtypes: datetime64[ns](2), float64(50), string(3)
memory usage: 62.9 MB

In [35]:
 #Final check for missing values
print("\nFinal check for missing values:")
print(df.isnull().sum())

Final check for missing values:
Bearer Id                                   0
Start                                       1
Start ms                                    0
End                                         1
End ms                                      0
Dur. (ms)                                   0
IMSI                                        0
MSISDN/Number                               0
IMEI                                        0
Last Location Name                          0
Avg RTT DL (ms)                             0
Avg RTT UL (ms)                             0
Avg Bearer TP DL (kbps)                     0
Avg Bearer TP UL (kbps)                     0
TCP DL Retrans. Vol (Bytes)                 0
TCP UL Retrans. Vol (Bytes)                 0
DL TP < 50 Kbps (%)                         0
50 Kbps < DL TP < 250 Kbps (%)              0
250 Kbps < DL TP < 1 Mbps (%)               0
DL TP > 1 Mbps (%)                          0
UL TP < 10 Kbps (%)                         0
10 Kbps < UL TP < 50 Kbps (%)               0
50 Kbps < UL TP < 300 Kbps (%)              0
UL TP > 300 Kbps (%)                        0
HTTP DL (Bytes)                             0
HTTP UL (Bytes)                             0
Activity Duration DL (ms)                   0
Activity Duration UL (ms)                   0
Dur. (ms).1                                 0
Handset Manufacturer                        0
Handset Type                                0
Nb of sec with 125000B < Vol DL             0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 37500B < Vol UL              0
Nb of sec with 6250B < Vol DL < 31250B      0
Nb of sec with 6250B < Vol UL < 37500B      0
Nb of sec with Vol DL < 6250B               0
Nb of sec with Vol UL < 1250B               0
Social Media DL (Bytes)                     0
Social Media UL (Bytes)                     0
Google DL (Bytes)                           0
Google UL (Bytes)                           0
Email DL (Bytes)                            0
Email UL (Bytes)                            0
Youtube DL (Bytes)                          0
Youtube UL (Bytes)                          0
Netflix DL (Bytes)                          0
Netflix UL (Bytes)                          0
Gaming DL (Bytes)                           0
Gaming UL (Bytes)                           0
Other DL (Bytes)                            0
Other UL (Bytes)                            0
Total UL (Bytes)                            0
Total DL (Bytes)                            0
dtype: int64

In [36]:
df.to_csv('../data/cleaned_telecom_data.csv', index=False)